export const UI_TEXT = {
  metadata: {
    language: "es",
    title: "Op rebote en bolsa",
    description: "Oportunidades de rebote en bolsa para torpes y no tan torpes. Swing trading y gestión de universo de acciones.",
  },
  brand: "Op Rebote",
  navigation: {
    home: "Inicio",
    opportunities: "Oportunidades",
    watchlist: "Seguimiento",
    companies: "Empresas radar",
    open: "Abrir navegación",
    close: "Cerrar navegación",
    expand: "Expandir navegación",
    collapse: "Encoger navegación",
    main: "Navegación principal",
  },
  pages: {
    opportunities: {
      title: "Oportunidades de rebote",
      description: "Empresas candidatas a oportunidades de rebote.",
      emptyTitle: "No hay oportunidades disponibles",
      emptyDescription: "El último análisis no encontró candidatas. Actualiza las oportunidades para volver a analizar el radar.",
      statValid: "Candidatas filtradas",
      allPassedFilters: "Todas pasan los filtros base",
      statComplete: "Cumplen todos los parámetros",
      statOneMissing: "Falta un parámetro",
    },
    watchlist: {
      title: "Empresas en seguimiento",
      description: "Acciones marcadas para monitorizar su evolución, confirmación de rebote y niveles clave.",
      statTotal: "Total en Seguimiento",
      statOversold: "En Sobreventa (RSI ≤ 30)",
      statAboveFloor: "Sobre Soporte / Suelo",
      goToOpportunities: "Ir a Oportunidades",
      goToRadar: "Explorar Empresas Radar",
    },
    companies: {
      title: "Empresas radar",
      description: "Empresas que se han detectado como candidatas para ser incluidas en el radar.",
      addButton: "Añadir empresa",
      addTitle: "Añadir empresa al radar",
      addDescription: "Busca por nombre o ticker.",
      addPlaceholder: "Nombre o ticker",
      addSearch: "Buscar",
      addSearching: "Buscando...",
      addSaving: "Añadiendo...",
      addSelect: "Añadir",
      addClose: "Cerrar",
      addEmptyQuery: "Escribe un nombre o ticker para buscar.",
      addAlreadyExists: "Esta empresa ya aparece en Empresas Radar.",
      addAlreadySavedLabel: "Ya está en el radar",
      addNotFound: "No encontramos ninguna acción con ese nombre o ticker en Yahoo Finance.",
      addSearchError: "No se pudo consultar Yahoo Finance. Inténtalo de nuevo.",
      addInvalid: "Yahoo no devolvió una cotización válida de una acción para añadir.",
      addSuccess: (name: string) => `${name} se añadió a Empresas Radar.`,
    },
  },
  login: {
    heading: "Acceso Restringido",
    emailPlaceholder: "Correo electrónico",
    passwordPlaceholder: "Contraseña",
    submit: "Entrar",
  },
  buttons: {
    sync: "Buscar empresas",
    syncing: "Buscando...",
    updateQuotes: "Actualizar cotizaciones",
    updatingQuotes: "Escaneando...",
    search: "Actualizar oportunidades",
    searching: "Buscando...",
  },
  loading: {
    sync: "Buscando empresas candidatas...",
    updateQuotes: "Escaneando empresas del radar...",
    search: "Buscando oportunidades...",
  },
  table: {
    titles: {
      TIER_0: "Dividend Kings en rebote",
      TIER_1: "Candidatas prioritarias de rebote",
      TOP: "Gran capitalización (TOP)",
      MID: "Capitalización media (MID)",
    },
    subtitles: {
      TIER_0: "Sobreventa y filtros de calidad superados",
    },
    columns: {
      follow: "Seguir",
      ticker: "Ticker",
      name: "Nombre",
      price: "Precio",
      rsi: "RSI",
      volume: "Volumen",
      volumeAndRelative: "Volumen / RVOL",
      relativeVolume: "Volumen relativo",
      fundamentals: "Fundamentales",
      recentFloor: "Suelo reciente",
      sma200: "vs SMA200",
      lastPrice: "Último precio",
      previousDayChange: "Variación respecto al último escaneo del día anterior",
      sector: "Sector",
      dividend: "Dividendo",
      dividendYield: "Rentabilidad por dividendo",
      searchByNameOrTicker: "Buscar por nombre o ticker",
      backtest: "Backtest histórico",
      actions: "Acciones",
      status: "Estado rebote",
      filters: "Filtros de estrategia",
    },
    backtestBySmaTitle: "% de aciertos históricos según el precio estuviera por encima o por debajo de la SMA200 al dar la señal.",
    filters: {
      priceAriaLabel: "Filtrar por variación del precio",
      priceAll: "Último precio: Todos",
      priceUp: "Último precio: Subida",
      priceDown: "Último precio: Bajada",
      dividendAriaLabel: "Filtrar por dividendo",
      dividendAll: "Dividendo: Todos",
      dividendYes: "Dividendo: Sí",
      dividendNo: "Dividendo: No",
      sectorAriaLabel: "Filtrar por sector",
      sectorAll: "Todos los sectores",
      clear: "Limpiar filtros",
      noResults: "No hay empresas que coincidan con los filtros.",
    },
    values: {
      dividendYes: "Sí",
      dividendNo: "No",
      dividendKing: "Dividend King",
      dividendAristocrat: "Dividend Aristocrat",
      unknownSector: "Desconocido",
      notAvailable: "-",
      noData: "Sin datos",
      relativeVolumeAboveAverage: "volumen sobre la media",
      relativeVolumeBelowAverage: "volumen bajo la media",
      relativeVolumeAtAverage: "volumen en la media",
      rsiRecovering: "RSI ha recuperado el umbral de sobreventa",
      rsiPossibleTurn: "RSI sube en sobreventa; posible giro, aún sin confirmar",
      rsiRising: "RSI subiendo",
      rsiFalling: "RSI bajando",
      rsiUnchanged: "RSI sin cambio respecto a la sesión anterior",
      rsiNoPreviousValue: "Sin RSI de la sesión anterior",
      rsiNoComparison: "sin dato anterior para comparar",
      possibleTurn: "posible giro",
      followActive: "Siguiendo (clic para quitar)",
      followInactive: "Seguir esta empresa",
      unfollow: "Dejar de seguir",
      showFilters: "Mostrar filtros de estrategia",
      hideFilters: "Ocultar filtros de estrategia",
    },
    filterDetails: {
      heading: "Fundamentales de la empresa",
      threshold: "Umbral",
      pass: "Cumple",
      fail: "No cumple",
      currentRatio: "Liquidez corriente",
      debtToEquity: "Deuda / patrimonio",
      roe: "ROE",
    },
    guide: {
      title: "Guía rápida de indicadores",
      floorTitle: "Suelo reciente.",
      floorAbove: "precio sobre el mínimo",
      floorBelow: "por debajo, posible ruptura del mínimo",
      rsiTrendUp: "RSI sube; en sobreventa, posible giro",
      rsiTrendDown: "RSI baja",
      rsiTrendStable: "RSI sin cambio",
      smaTitle: "vs SMA200.",
      smaDescription: "Distancia frente a la media de 200 sesiones; negativo significa que cotiza por debajo.",
      volumeTitle: "RVOL.",
      volumeDescription: "Actividad frente a la media reciente; no indica compras o ventas.",
      backtestTitle: "Backtest.",
      backtestDescription: "Resultados históricos:",
      backtestWon: "Ganó",
      backtestStalled: "Se estancó",
      backtestLost: "Perdió",
      scoreTitle: "Resumen: ",
      scoreDescription: [
        "RSI por debajo del umbral de sobreventa = presión vendedora; cuanto más bajo, más extrema es la sobreventa.",
        "RVOL > 1x = más volumen que la media reciente, pero este dato por sí solo no permite saber si predominan las compras o las ventas.",
        "Suelo reciente cerca de 0% = precio cerca del mínimo.",
        "SMA200 > 0% = precio por encima de la media; entre −10% y 0% sigue por debajo, pero aún cumple el criterio de proximidad.",
        "Backtest: busca al menos 20 casos, con más operaciones ganadoras que perdedoras y no más del 50% estancadas.",
        "Todos estos datos son indicios, no una garantía.",
      ].join("\n"),
      rsiTitle: "RSI.",
      rsiDescription: "Mide la fuerza reciente del movimiento. Un valor bajo indica sobreventa, pero no confirma un rebote.",
      currentRatioTitle: "Liquidez corriente.",
      currentRatioDescription: "Activos corrientes frente a deudas a corto plazo; estima capacidad de pago inmediata.",
      debtToEquityTitle: "D/E.",
      debtToEquityDescription: "Deuda frente a patrimonio; cuanto menor, menos apalancamiento financiero.",
      roeTitle: "ROE.",
      roeDescription: "Rentabilidad sobre fondos propios; mide cuánto beneficio genera respecto al patrimonio.",
    },
    formatting: {
      percentageUnit: "%",
    },
    pagination: {
      companyRecords: "empresas",
      opportunityRecords: "oportunidades",
      watchlistRecords: "en seguimiento",
      defaultRecords: "registros",
      pageSize: "Ver",
      previousPage: "Página anterior",
      nextPage: "Página siguiente",
      page: "Página",
      pageOf: "de",
      mobilePageSeparator: "/",
    },
    emptyStates: {
      default: "No hay registros para mostrar.",
      companies: "No hay empresas en esta categoría.",
      noCompaniesMatchSearch: "No hay empresas que coincidan con la búsqueda.",
      opportunities: "No hay oportunidades que cumplan el segundo filtro.",
      watchlist: "No tienes ninguna empresa en seguimiento. Puedes marcar empresas usando el icono de favoritos en la pantalla de Oportunidades o en Empresas Radar.",
      watchlistFilter: "No hay empresas en seguimiento que coincidan con la búsqueda.",
    },
    sorting: {
      byColumn: (label: string) => `Ordenar por ${label.toLowerCase()}`,
    },
  },
  floor: {
    underMinimum: "bajo el mínimo",
    overMinimum: "sobre el mínimo",
    description: "Distancia entre el precio actual y el mínimo de las cinco velas previas. No es una estimación de caída máxima.",
  },
  feedback: {
    syncError: "Error al sincronizar con el mercado.",
    searchError: "Error al buscar oportunidades.",
    radarScanComplete: "Escaneo completado; historial actualizado.",
    noYahooCompanies: "No se encontraron empresas en Yahoo.",
    syncDatabaseError: "Hubo un error al guardar en la base de datos.",
    searchFailure: "No se pudieron buscar nuevas oportunidades.",
    searchCompleted: (companyCount: number, opportunityCount: number) =>
      `Se analizaron ${companyCount} empresas del radar y se encontraron ${opportunityCount} rebotes.`,
    syncCompleted: (companyCount: number) =>
      `¡Sincronización completada! Se procesaron ${companyCount} empresas del mercado.`,
  },
} as const;