export const UI_TEXT = {
  metadata: {
    language: "es",
    title: "Op rebote en bolsa",
    description: "Oportunidades de rebote en bolsa para torpes y no tan torpes. Swing trading y gestión de universo de acciones.",
  },
  brand: "Op Rebote",
  navigation: {
    home: "Inicio",
    opportunities: "Oportunidades",
    companies: "Empresas radar",
    open: "Abrir navegación",
    close: "Cerrar navegación",
    expand: "Expandir navegación",
    collapse: "Encoger navegación",
    main: "Navegación principal",
  },
  pages: {
    opportunities: {
      title: "Oportunidades de rebote",
      description: "Empresas candidatas a oportunidades de rebote.",
    },
    companies: {
      title: "Empresas radar",
      description: "Empresas que se han detectado como candidatas para ser incluidas en el radar.",
    },
  },
  login: {
    heading: "Acceso Restringido",
    emailPlaceholder: "Correo electrónico",
    passwordPlaceholder: "Contraseña",
    submit: "Entrar",
  },
  buttons: {
    sync: "Buscar empresas",
    syncing: "Buscando...",
    updateQuotes: "Actualizar cotizaciones",
    updatingQuotes: "Escaneando...",
    search: "Actualizar oportunidades",
    searching: "Buscando...",
  },
  loading: {
    sync: "Buscando empresas candidatas...",
    updateQuotes: "Escaneando empresas del radar...",
    search: "Buscando oportunidades...",
  },
  table: {
    titles: {
      TIER_0: "Dividend Kings en rebote",
      TIER_1: "Candidatas prioritarias de rebote",
      TOP: "Gran capitalización (TOP)",
      MID: "Capitalización media (MID)",
    },
    subtitles: {
      TIER_0: "Sobreventa y filtros de calidad superados",
    },
    columns: {
      ticker: "Ticker",
      name: "Nombre",
      price: "Precio",
      rsi: "RSI",
      volume: "Volumen",
      recentFloor: "Suelo reciente",
      lastPrice: "Último precio",
      previousDayChange: "Variación respecto al último escaneo del día anterior",
      sector: "Sector",
      dividend: "Dividendo",
      dividendYield: "Rentabilidad por dividendo",
      searchByNameOrTicker: "Buscar por nombre o ticker",
    },
    filters: {
      priceAriaLabel: "Filtrar por variación del precio",
      priceAll: "Variación: todas",
      priceUp: "Variación: al alza",
      priceDown: "Variación: a la baja",
      dividendAriaLabel: "Filtrar por dividendo",
      dividendAll: "Dividendo: todos",
      dividendYes: "Con dividendo",
      dividendNo: "Sin dividendo",
      sectorAriaLabel: "Filtrar por sector",
      sectorAll: "Todos los sectores",
      clear: "Limpiar filtros",
      noResults: "No hay empresas que coincidan con los filtros.",
    },
    values: {
      dividendYes: "Sí",
      dividendNo: "No",
      dividendKing: "Dividend King",
      dividendAristocrat: "Dividend Aristocrat",
      unknownSector: "Desconocido",
      notAvailable: "-",
      noData: "Sin datos",
    },
    formatting: {
      percentageUnit: "%",
    },
    pagination: {
      companyRecords: "empresas",
      opportunityRecords: "oportunidades",
      defaultRecords: "registros",
      pageSize: "Ver",
      previousPage: "Página anterior",
      nextPage: "Página siguiente",
      page: "Página",
      pageOf: "de",
      mobilePageSeparator: "/",
    },
    emptyStates: {
      default: "No hay registros para mostrar.",
      companies: "No hay empresas en esta categoría.",
      noCompaniesMatchSearch: "No hay empresas que coincidan con la búsqueda.",
      opportunities: "No hay oportunidades que cumplan el segundo filtro.",
    },
    sorting: {
      byColumn: (label: string) => `Ordenar por ${label.toLowerCase()}`,
    },
  },
  floor: {
    underMinimum: "bajo el mínimo",
    overMinimum: "sobre el mínimo",
    description: "Distancia entre el precio actual y el mínimo de las cinco velas previas. No es una estimación de caída máxima.",
  },
  feedback: {
    syncError: "Error al sincronizar con el mercado.",
    searchError: "Error al buscar oportunidades.",
    radarScanComplete: "Escaneo completado; historial actualizado.",
    noYahooCompanies: "No se encontraron empresas en Yahoo.",
    syncDatabaseError: "Hubo un error al guardar en la base de datos.",
    searchFailure: "No se pudieron buscar nuevas oportunidades.",
    searchCompleted: (companyCount: number, opportunityCount: number) =>
      `Se analizaron ${companyCount} empresas del radar y se encontraron ${opportunityCount} rebotes.`,
    syncCompleted: (companyCount: number) =>
      `¡Sincronización completada! Se procesaron ${companyCount} empresas del mercado.`,
  },
} as const;